### ISSUE TITLE
disable E2E encryption

### ISSUE THREAD

**Issue by ChameleonScales** [marius-wieschollek/passwords-webextension#125]
I enabled client-side E2E encryption and realized it wasn't working with the Android app, so I'd like to disable it for the moment but I don't see any way to do so.
Of course as soon as the Android app catches on I can have it enabled but there could be other reasons why one would want to disable it, so I think it would be a useful feature anyway.

**Comment by ChameleonScales** [comment]
I ended up using the "Delete all" button after backing up and when I re-imported the database, encryption was not enabled, so problem solved for me. A disable button for encryption could still be there to make it simpler but it's less important for me now.

**Comment by marius-wieschollek** [comment]
Please stick to the feature request form and don't post questions as an issue.

Since the app also supports hidden passwords, folders and tags, there is always a possibility that some encrypted elements are not visible to the client which would perform the removal of the decryption. It is also possible that a different client is not aware that encryption has been disabled when it saves a password. In that situation the client would write encrypted data which can't be decrypted anymore.
Therefore there is no implemented way to disable the encryption.

You can restore a [backup](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Backups) or you can export all passwords, delete everything and import them again.

**Comment by ChameleonScales** [comment]
It was actually a feature request even though I found a workaround. But if you say it can't be implemented, no problem. The workaround is good enough.
