### ISSUE TITLE
[Password mining] Have an ignore list

### ISSUE THREAD

**Issue by bertwesarg** [marius-wieschollek/passwords-webextension#140]
**Current Status**
I constantly get notified about new passwords, which I do not want to store in the password manager. But I do not see a possibility to ignore these in the future.

**Feature Description**
An ignore list would be very useful, I think.

**Comment by bertwesarg** [comment]
This is getting more frustrating every day. On a normal work-day, the mining collects around 10 **new** passwords, which I do not want to store in the cloud, from around 3-4 sites. But the extension keeps the passwords in memory, until I remove them from the _Collected_ list.

**Comment by marius-wieschollek** [comment]
I'm happy to accept a PR for this.

**Comment by bertwesarg** [comment]
This isn't very surprising, thus I'm not sure, what this adds to the discussion? For example, for now I'm thinking of a per-server ignore list. That could help in a multi-account scenario. Though does this make sense at all? Should the ignore list only match the host or also the user?

Also, is keeping the newly discovered passwords in memory for an unspecified time, not a security concern to you?

**Comment by marius-wieschollek** [comment]
> This isn't very surprising, thus I'm not sure, what this adds to the discussion?

I think this feature is useful, but i'm not going to get to it anytime soon. If you or anyone else want this feature sooner, i'm happy to accept a PR for this, otherwise it will take time.

> For example, for now I'm thinking of a per-server ignore list. That could help in a multi-account scenario.

Currently you can only save credentials in your main account. But it could be useful if you have separate accounts for work and private and maybe don't want to set up your work account on a private pc but also don't want to get notified every time you log in a work site.

> Also, is keeping the newly discovered passwords in memory for an unspecified time, not a security concern to you?

No. I can't think of a scenario where this would be a bigger risk than the search tab right next to it.

**Comment by pkrolkgp** [comment]
> > Also, is keeping the newly discovered passwords in memory for an unspecified time, not a security concern to you?
> 
> No. I can't think of a scenario where this would be a bigger risk than the search tab right next to it.
If i log to bank site, but dont wan't to remember password, and the password is cached in memory, the attacker could click save password, and use saved credidentials to read this password or log to website i don't wanna my credidentials saved.

**Comment by marius-wieschollek** [comment]
#253
