### ISSUE TITLE
Feature for better security

### ISSUE THREAD

**Issue by ttjaden** [marius-wieschollek/passwords-webextension#17]
First of all: Great and good looking App+Addon!!!
But: In my opinion there is a big security issue. When starting firefox there is no need of typing a master password or each time the login phrase for the nextcloud instance. So withoout typing any kind of password a person can check all passwords stored over the password-app in the nextcloud.

Tools like Keeweb etc. solve this by locking the connection after a few minutes e.g. Would this also be possible in the firefox-extension?

**Comment by marius-wieschollek** [comment]
Master password, client side encryption and session duration limits are features which are currently under development for the passwords app. They will be ready to test within the next months in the nightly builds. Since this are features of the main app this issue is a little bit off topic for the webextension. However the version 2 of the extension will support all this as well.
