### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by AllirionX** [marius-wieschollek/passwords-webextension#170]
I am hosting nextcloud on a raspberry pi and use dnsmasq to map the hostname `cloud.myhostname.com` to the nextcloud pi.

When on the LAN the first connection to the Nextcloud account fails. 
After starting the browser the extension throws:

`{"details":{"data":{},"message":"Failed to fetch","stack":"TypeError: Failed to fetch","time":1618185666684},"error":{"name":"TypeError","stack":"TypeError: Failed to fetch","string":"TypeError: Failed to fetch","message":"Failed to fetch"}}`

Then:

`{"details":{"data":{"message":"Could not establish connection. Receiving end does not exist."},"stack":"Error\n    at Object._getDetailsFromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:6377)\n    at Object._addError (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:5736)\n    at Object.logError (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:5544)\n    at Object._sendMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:11610)\n    at async Promise.all (index 0)\n    at async Object._sendMessages (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:11831)","time":1618185885901},"error":{"message":"Could not establish connection. Receiving end does not exist."}}`

However:
- accessing `cloud.myhostname.com` works flawlessly for other apps (browser, nextcloud client etc.)
- if I access the Browse extension tab, force a refresh on the Nextcloud Account then I am able to access my passwords. That makes me think that the problem comes from the way the extension handles the first connection?

**Comment by sscraggles** [comment]
same problem

**Comment by flo-mic** [comment]
@AllirionX and @sscraggles  it must not be a issue with the extension. Maybe your dns just answeres to slow on the first conenction and as soon as you open the main url the correct dns name is already cached due to the request of the extension. 

Please disable the extension for a moment and restart your computer. Open a browser and navigate to the url of your nextcloud instance. Check if it is loading directly or if there is a small time where you see a message like unavailable until the browser performs an automatic reload.

**Comment by AllirionX** [comment]
I upgraded everything to the last version this week-end (passwords app in nextcloud, extension in chrome) and the problem disappeared. 
I can say for sure what was causing the problem.
