### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by marius-wieschollek** [marius-wieschollek/passwords-webextension#2]
@pafcioooo Since the new passwords app is nearly ready, it is time to get this experiment started. I have added the automated polish translation [here](https://github.com/marius-wieschollek/passwords-webextension/blob/master/src/platform/generic/_locales/pl/messages.json), and i would like you to review it and tell me how good it actually was.

**Comment by pafcioooo** [comment]
I see there some mistakes. How can I correct them?

**Comment by marius-wieschollek** [comment]
1. Fork the app
2. Edit the file [src/platform/generic/_locales/pl/messages.json](https://github.com/marius-wieschollek/passwords-webextension/blob/master/src/platform/generic/_locales/pl/messages.json) using the [English translation for reference](https://github.com/marius-wieschollek/passwords-webextension/blob/master/src/platform/generic/_locales/en/messages.json)
3. Create a pull request

I think you can even just click edit on the file on github

**Comment by pafcioooo** [comment]
Done.

**Comment by marius-wieschollek** [comment]
Great. Thank you.
What would you say about the general quality of the automated translation?
Was it grammatically or contextually incorrect? Or was it more that the translations were badly chosen?

**Comment by pafcioooo** [comment]
General quality is 50% as you can see the amount of what I have changed. And both grammatically and contextually with one or two translations badly chosen (funny: "match" was translated as equivalent of "game", instead of "fit" synonym).The Polish language is difficult in general. 

It would be faster to correct if translation file had also the field  "description" for each entry being translated, like in English translation reference file eg.  "description": "Shown when the related page did not find any results". But anyway it is not a problem. I am glad I could help:-)
