### ISSUE TITLE
Handling non-ascii characters

### ISSUE THREAD

**Issue by lapete** [marius-wieschollek/passwords-webextension#44]
I noticed some bugs when I used German umlauts (ä ö ü) in this extension with a current version of firefox, nextcloud 15.0.2 and (K)Ubuntu 18.04 on the client side.

1. When I had an umlaut in my nextcloud password, this extension could not retrieve the password list and showed a error message "Authorisation failed" (no other nextcloud app had problems with the specific password). When I set a password without umlauts, it worked fine.
2. When I had an umlaut in a username for a music board, I could not get the login data for the specific page, neither with the auto detection, nor with the search module. Retrieving the data from the webapp worked perfectly fine, but not with the ff extenseion. Tested with another account, it worked after I deleted the ones with the umlauts.

There seem to be issues with character encoding in this extension.

**Comment by marius-wieschollek** [comment]
I can confirm the issue with the umlauts in the password. The password and username need to be base64 encoded for the authentication for the Nextcloud API, but the native JavaScript base64 encoder will produce results which are nonstandard for non-ASCII characters. This issue will be fixed in the next release. As a workaround you can use an app password for the extension.

I can not reproduce the second issue. Logins with umlaits in the password or username seem to work just fine for me. (FF 64, Ubuntu 18.04) Can you add more details so i can reproduce the issue?

**Comment by lapete** [comment]
I tested it again and can't reproduce it now, after I deleted all related logins. Maybe I had some corrupt stored data.
Thank you for your quick response and the planned fix!

**Comment by marius-wieschollek** [comment]
With the release of 1.8.0 this issue should now be fixed.
