### ISSUE TITLE
Saved password is ".............." at blizzard battle net

### ISSUE THREAD

**Issue by cracker0dks** [marius-wieschollek/passwords-webextension#50]
I typed my username and password on: 
https://eu.battle.net/login/de/ -> enter

I got a promt "Click here to save password" -> clicked it. Saved password in nextcloud was ".............." (yes the char dot "." multible times -> and yes, I clicked on the eye icon :)

this function is working on other sites without a problem so far.

**Comment by marius-wieschollek** [comment]
It seems to me like blizzard is using a system where the password is processed in the browser instead of sending it to the server. When you click the login button, the site replaces the password with a series of dots. 

I'm not sure if i can do much here. As a workaround you can just set the correct password in the Nextcloud app and then synchronize it to the extension.

**Comment by cracker0dks** [comment]
At some point it will be send to the server... maybe we can save and send that pw/hash? Or Read the pw from the input befor it is overwritten with dots?

Anyway, I will do it with your workaround for now. Thanks.
