### ISSUE TITLE
IE webextension

### ISSUE THREAD

**Issue by JulesBalgue** [marius-wieschollek/passwords-webextension#63]
Hi, 

I wanted to know if it was planned to do a webextension for internet explorer ?
We eventually need it for our company.
Thank you ! :) 

Jules

**Comment by marius-wieschollek** [comment]
You mean the actual Microsoft Internet Explorer? No.
But when Microsoft Edge switches to the Chrome Engine I will look into supporting it.

**Comment by JulesBalgue** [comment]
Hi,

Ok but we are on Windows server 2016 and it's not currently support MS Edge… So have you got a solution ? 

Ty

Jules

**Comment by marius-wieschollek** [comment]
The Internet Explorer does not support Web-Extensions. It is unlikely that it ever will.

I would have to write and maintain a new extension just for that dying browser.
I'm not even sure if it is even possible since our client side encryption requires WASM, but MSIE does not support it.

Either you can look at our [developer documentation](https://git.mdns.eu/nextcloud/passwords/wikis/Developers/Index) and write an extension yourself, or you can switch to a more modern browser.
