### ISSUE TITLE
Auto-fill fails on all Discourse forums

### ISSUE THREAD

**Issue by ChameleonScales** [marius-wieschollek/passwords-webextension#75]
I'm a member of about a dozen Discourse forums and the auto-fill button never works on them. It always leads to a page saying:
"Oops! that page doesn't exist or is private." and doesn't log me in.

I can of course use the "copy to clipboard" buttons but it's something you might want to know.

**Comment by marius-wieschollek** [comment]
If you want to, you can try if this still happens with the experimental version 2.0. 

You can download it for [Firefox here](https://git.mdns.eu/nextcloud/passwords-webextension/-/jobs/artifacts/testing/browse/dist/firefox-extension?job=Publish+Nightly+Firefox) or [Chrome here](https://chrome.google.com/webstore/detail/aipncmjoigmhooiiclcailmhiopachih). I would recommend Firefox, because the version in the Chrome Web Store always lags behind by some days.

**Comment by majkinetor** [comment]
Experimental version works for me where other one doesn't.

**Comment by ChameleonScales** [comment]
ok it clearly works now. Thanks for the fix!
